### ISSUE TITLE
⁠max_tokens not working in the ChatBedrockConverse

### ISSUE THREAD

**Issue by idotr7** [langchain-ai/langchain-aws#257] opened 2024-10-27 14:56 UTC
I initialiszed the BaseChatModel with max tokens but when stream as follows:
stream_model = chat_model.with_config(tags=["should_stream"])
response = await stream_model.ainvoke([system_message, human_message], config=config)

but the tokens keep rising above the max_tokens of 200 i defined below:
def load_chat_model() -> BaseChatModel:
    """Load a chat model from a fully specified name.

    Args:
        fully_specified_name (str): String in the format 'provider/model'.
    """
    model = os.getenv("LLM") or "anthropic.claude-3-haiku-20240307-v1:0"
    return ChatBedrockConverse(
        name= os.getenv("API_TRACKING"),
        client=init_bedrock_client(),
        model=model,
        region_name="us-west-2",
        max_tokens=200
    )

**Comment by 3coins** [comment] 2024-10-28 22:48
@idotr7
Here is a simplified sample, that I ran and can't reproduce the issue that you reported. I have printed the params that are passed in the converse call, and it is correctly passed to the API.

```python
from langchain_aws import ChatBedrockConverse
import asyncio


async def main():
    llm = ChatBedrockConverse(
        model="anthropic.claude-3-haiku-20240307-v1:0",
        max_tokens=200
    )

    response = await llm.ainvoke("What is the capital of France? Answer in 500 words.")
    print(response)

if __name__ == "__main__":
    asyncio.run(main())
```

**Params passed**
```
{'modelId': 'anthropic.claude-3-haiku-20240307-v1:0', 'inferenceConfig': {'maxTokens': 200}}
```

**Output**
```
content="The capital of France is Paris.\n\nParis, the City of Light, is a global center of art, fashion, gastronomy, and culture. It is a city that has captured the imagination of people around the world, and it has been the capital of France for centuries.\n\nLocated on the banks of the Seine River, Paris is a city that is renowned for its stunning architecture, from the iconic Eiffel Tower to the grand Notre-Dame Cathedral. The city is divided into 20 arrondissements, or districts, each with its own unique character and charm.\n\nThe heart of Paris is the Île de la Cité, an island in the Seine that is home to some of the city's most famous landmarks, including the Notre-Dame Cathedral and the Conciergerie, a former royal palace that is now a museum.\n\nThe city is also known for its vibrant cultural scene, with world-class museums like the Louvre" additional_kwargs={} response_metadata={'ResponseMetadata': {'RequestId': 'f3c22dd4-64bc-444b-8f5b-2b8699e2d6a2', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Mon, 28 Oct 2024 22:42:39 GMT', 'content-type': 'application/json', 'content-length': '1040', 'connection': 'keep-alive', 'x-amzn-requestid': 'f3c22dd4-64bc-444b-8f5b-2b8699e2d6a2'}, 'RetryAttempts': 0}, 'stopReason': 'max_tokens', 'metrics': {'latencyMs': 1860}} id='run-76506e4c-ea1a-49cb-b61e-50ad941d642c-0' usage_metadata={'input_tokens': 21, 'output_tokens': 200, 'total_tokens': 221}
```

Let me know if I missed anything.

**Comment by 3coins** [comment] 2024-12-09 22:34
@idotr7 
Closing this issue, as there has been a response for more than a month. Please feel free to re-open if this issue persists.

**Closed by 3coins** 2024-12-09 22:34 UTC
Labels: can't reproduce
