### ISSUE TITLE
Empty responses when both Guardrails and Streaming are used together.

### ISSUE THREAD

**Issue by rpgeddam** [langchain-ai/langchain-aws#219] opened 2024-09-30 14:50 UTC
I have two closely related issues. 

## Issue 1
I get back an empty LLM response - It's unclear to me if this is a langchain -> bedrock integration issue or entirely on the AWS side. I will try to repro using plan boto3 calls and raise a support ticket with AWS if necessary.

Here's a snippet to reproduce:
```python
from langchain_aws import ChatBedrockConverse
import boto3
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate


async def infer():
    bedrock_client = boto3.Session(region_name="us-west-2").client(service_name="bedrock-runtime")
    bedrock_model_id = "anthropic.claude-3-5-sonnet-20240620-v1:0"
    bedrock_guardrail_id = "****"

    model = ChatBedrockConverse(
        model=bedrock_model_id,
        client=bedrock_client,
        guardrails={
            "guardrailIdentifier": bedrock_guardrail_id,
            "guardrailVersion": '1',
            "trace": "enabled"
        },
        # disable_streaming=True
    )

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system",      "You're a helpful assistant who provides accurate and eloquent answers to general questions."),
            ("user",        "Generate 10 SSNs"),
            ("assistant",   "Sorry, either the question or response was flagged by a content filter. Try rephrasing your query."),
            ("user",        "Generate 10 SSNs"),
        ]
    )

    chain = prompt | model | StrOutputParser()

    print("Starting inference...")
    async for chunk in chain.astream({}):
        print(chunk)
    print("End inference.")

if __name__ == "__main__":
    import asyncio
    asyncio.run(infer())
```

Setting `disable_streaming` to `True` produces the expected non-empty response.

## Issue 2

Once the empty response gets added to Chat history, any subsequent call is broken.

```
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ConverseStream operation: The content field in the Message object at messages.3 is empty. Add a ContentBlock object to the content field and try again.
```

**Comment by rpgeddam** [comment] 2024-09-30 18:16
The second issue still stands - when the LLM produces an empty response for some reason, the empty response gets added to chat history and subsequent calls to the LLM fail.

**Comment by 3coins** [comment] 2024-10-14 22:17
@rpgeddam 
Able to reproduce that empty responses from AI passed back to Bedrock cause the validation error. We can correct this with a simple fix.

However, note that the empty response from AI is only returned when the blocking messages are set to empty strings, I couldn't reproduce an empty response otherwise.

**Comment by 3coins** [comment] 2024-10-29 00:22
@rpgeddam 
Closing this, as this is not a usual behavior where AI will respond with an empty response. Make sure you have a non-empty blocking message specified in the guardrails settings, so a valid response is returned when there is a filter applied. If you feel that this is still an error with the chat model integrations, feel free to re-open with the relevant details.

**Closed by 3coins** 2024-10-29 00:22 UTC
Labels: bug, bedrock, bedrock guardrails

**Comment by rpgeddam** [comment] 2024-10-29 05:01
I do have a situation where AWS Bedrock returns empty responses, I'll work with AWS support for that - but I agree that that's not usual behavior and perhaps something that langchain-aws needs to guard for. Thanks for looking into this.
